### PR TITLE
Rename DP-Constraint => DiffPair-Constraint

### PR DESCRIPTION
**Pull request by tjknoth**
Literally just a rename

### CODE REVIEW

**Review by bhusang — APPROVED** [review]
Looks good -- also have to change user code that relies on this rsn. And while it's more typing, it's also much easier to understand what's going on (and not to mention avoids any salacious misunderstandings).

**Comment by callendorph** [comment]
I think you are missing the `src/protocols/pcie.stanza`. @bhusang merged it yesterday.

**Comment by tjknoth** [comment]
Good catch, got it.

**Comment by tjknoth** [comment]
I'm just going to merge and we can deal with user code as necessary?

**Review by callendorph — APPROVED** [review]
:+1: Thank you!

**Pull request merged**
