### PR TITLE
fixed up code to remove deprecation warnings

### PR DESCRIPTION
**Pull request by bhusang**
@callendorph this has some overlap with your existing PR. I can fixup the merge conflicts once approved and your PR has merged.

### CODE REVIEW

**Comment by callendorph** [comment]
I would suggest rebasing on my branch.

**Comment by bhusang** [comment]
Your branch has a conflict with `main` that also is now on my branch 😃

**Comment by callendorph** [comment]
I've resolved conflicts on my branch.

**Comment by bhusang** [comment]
@callendorph This PR is ready for review.

**Comment by callendorph** [comment]
This is not working and we need to do this in a different way.

I'm going to retract this PR and the other PR. 

I will create a PR that removes all `val stack` references because `stack` is now a preserved keyword. This will allow `main` on JSL to build on both `develop` and the JITX release. 

Then we can introduce 1 PR that has all of the changes that need to be made to support the syntax refactor.

**Pull request closed without merging**
