### PR TITLE
Improved instructions in the form of a README.md

### PR DESCRIPTION
**Pull request by bhusang**

### CODE REVIEW

**Comment by callendorph** [comment]
I think this branch is wrong - it seems a duplicate of the DisplayPort branch.

**Comment by bhusang** [comment]
It's added on to the DisplayPort branch -- when that merges to main, then I will merge this one.

**Comment by callendorph** [comment]
This branch doesn't change the README

**Comment by callendorph** [comment]
I don't know what has changed on this branch. Can you please rebase from main and force push ?

**Comment by bhusang** [comment]
Done.

**Review by callendorph — APPROVED** [review]
Seems like most of the content was in the other PR.

**Pull request merged**
