### PR TITLE
Rename make-pin

### PR DESCRIPTION
**Pull request by tjknoth**
Will merge once the jitx-client updates are released.

### CODE REVIEW

**Comment by tjknoth** [comment]
jitx-client PR is merged; will merge this once release goes out

**Comment by callendorph** [comment]
With `3.18.0` released - can we please get this merged ?

**Comment by tjknoth** [comment]
> With `3.18.0` released - can we please get this merged ?

The tests still aren't passing in CI -- is that supposed to be using an up-to-date jitx-client? should I just force merge?

**Comment by callendorph** [comment]
```
jitx-client-1  | src/bundles/comms.stanza:40.19: No appropriate function 'make-port' for argument types (Symbol). Possibilities are:
jitx-client-1  |   make-port: (Symbol, PortType) -> Pin in package 'jitx/commands'
jitx-client-1  | 
jitx-client-1  | src/bundles/comms.stanza:41.19: No appropriate function 'make-port' for argument types (Symbol). Possibilities are:
jitx-client-1  |   make-port: (Symbol, PortType) -> Pin in package 'jitx/commands'
jitx-client-1  | 
jitx-client-1  | src/bundles/comms.stanza:131.16: No appropriate function 'make-port' for argument types (Symbol). Possibilities are:
jitx-client-1  |   make-port: (Symbol, PortType) -> Pin in package 'jitx/commands'
jitx-client-1  | 
jitx-client-1  | src/bundles/comms.stanza:132.17: No appropriate function 'make-port' for argument types (Symbol). Possibilities are:
jitx-client-1  |   make-port: (Symbol, PortType) -> Pin in package 'jitx/commands'
jitx-client-1  | 
jitx-client-1  | src/bundles/comms.stanza:133.17: No appropriate function 'make-port' for argument types (Symbol). Possibilities are:
jitx-client-1  |   make-port: (Symbol, PortType) -> Pin in package 'jitx/commands'
jitx-client-1  | 
jitx-client-1  | src/bundles/comms.stanza:207.15: No appropriate function 'make-port' for argument types (Symbol). Possibilities are:
jitx-client-1  |   make-port: (Symbol, PortType) -> Pin in package 'jitx/commands'
jitx-client-1  | 
jitx-client-1  | src/bundles/comms.stanza:273.17: No appropriate function 'make-port' for argument types (Symbol). Possibilities are:
jitx-client-1  |   make-port: (Symbol, PortType) -> Pin in package 'jitx/commands'
jitx-client-1  | 
jitx-client-1  | src/bundles/comms.stanza:274.17: No appropriate function 'make-port' for argument types (Symbol). Possibilities are:
jitx-client-1  |   make-port: (Symbol, PortType) -> Pin in package 'jitx/commands'
jitx-client-1  | 
jitx-client-1  | src/bundles/comms.stanza:275.17: No appropriate function 'make-port' for argument types (Symbol). Possibilities are:
jitx-client-1  |   make-port: (Symbol, PortType) -> Pin in package 'jitx/commands'
jitx-client-1  | 
jitx-client-1  | src/bundles/comms.stanza:276.17: No appropriate function 'make-port' for argument types (Symbol). Possibilities are:
jitx-client-1  |   make-port: (Symbol, PortType) -> Pin in package 'jitx/commands'
jitx-client-1  | 
jitx-client-1  | src/bundles/comms.stanza:277.17: No appropriate function 'make-port' for argument types (Symbol). Possibilities are:

```

Seems like we are using `make-port` wrong - no ?

**Comment by callendorph** [comment]
🤷

**Comment by tjknoth** [comment]
Hm apparently it is not in the version of jitx-client (tag 3.18.0-develop.29) that's running the tests

**Comment by tjknoth** [comment]
The correct code does seem to be in the release, however

**Comment by callendorph** [comment]
Ya - the docker image might not have the updated code ?

**Comment by callendorph** [comment]
Thanks Tristan!

**Pull request merged**
